/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/branches': RouteRecordInfo<'/branches', '/branches', Record<never, never>, Record<never, never>>,
    '/concept': RouteRecordInfo<'/concept', '/concept', Record<never, never>, Record<never, never>>,
    '/concept/': RouteRecordInfo<'/concept/', '/concept', Record<never, never>, Record<never, never>>,
    '/contacts': RouteRecordInfo<'/contacts', '/contacts', Record<never, never>, Record<never, never>>,
    '/devices': RouteRecordInfo<'/devices', '/devices', Record<never, never>, Record<never, never>>,
    '/faq': RouteRecordInfo<'/faq', '/faq', Record<never, never>, Record<never, never>>,
    '/InsideView': RouteRecordInfo<'/InsideView', '/InsideView', Record<never, never>, Record<never, never>>,
    '/MastersView': RouteRecordInfo<'/MastersView', '/MastersView', Record<never, never>, Record<never, never>>,
    '/MasterView': RouteRecordInfo<'/MasterView', '/MasterView', Record<never, never>, Record<never, never>>,
    '/MediaPostView': RouteRecordInfo<'/MediaPostView', '/MediaPostView', Record<never, never>, Record<never, never>>,
    '/MediaView': RouteRecordInfo<'/MediaView', '/MediaView', Record<never, never>, Record<never, never>>,
    '/NavView': RouteRecordInfo<'/NavView', '/NavView', Record<never, never>, Record<never, never>>,
    '/PolicyView': RouteRecordInfo<'/PolicyView', '/PolicyView', Record<never, never>, Record<never, never>>,
    '/PricesView': RouteRecordInfo<'/PricesView', '/PricesView', Record<never, never>, Record<never, never>>,
    '/ProceduresView': RouteRecordInfo<'/ProceduresView', '/ProceduresView', Record<never, never>, Record<never, never>>,
    '/ReviewInsideView': RouteRecordInfo<'/ReviewInsideView', '/ReviewInsideView', Record<never, never>, Record<never, never>>,
    '/ReviewView': RouteRecordInfo<'/ReviewView', '/ReviewView', Record<never, never>, Record<never, never>>,
    '/TechView': RouteRecordInfo<'/TechView', '/TechView', Record<never, never>, Record<never, never>>,
  }
}
