/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/branches': RouteRecordInfo<'/branches', '/branches', Record<never, never>, Record<never, never>>,
    '/concept/antiacne': RouteRecordInfo<'/concept/antiacne', '/concept/antiacne', Record<never, never>, Record<never, never>>,
    '/concept/bright': RouteRecordInfo<'/concept/bright', '/concept/bright', Record<never, never>, Record<never, never>>,
    '/concept/clear': RouteRecordInfo<'/concept/clear', '/concept/clear', Record<never, never>, Record<never, never>>,
    '/concept/detox': RouteRecordInfo<'/concept/detox', '/concept/detox', Record<never, never>, Record<never, never>>,
    '/concept/hydro': RouteRecordInfo<'/concept/hydro', '/concept/hydro', Record<never, never>, Record<never, never>>,
    '/concept/lifting': RouteRecordInfo<'/concept/lifting', '/concept/lifting', Record<never, never>, Record<never, never>>,
    '/concept/personal': RouteRecordInfo<'/concept/personal', '/concept/personal', Record<never, never>, Record<never, never>>,
    '/concept/red': RouteRecordInfo<'/concept/red', '/concept/red', Record<never, never>, Record<never, never>>,
    '/concepts': RouteRecordInfo<'/concepts', '/concepts', Record<never, never>, Record<never, never>>,
    '/contacts': RouteRecordInfo<'/contacts', '/contacts', Record<never, never>, Record<never, never>>,
    '/devices': RouteRecordInfo<'/devices', '/devices', Record<never, never>, Record<never, never>>,
    '/faq': RouteRecordInfo<'/faq', '/faq', Record<never, never>, Record<never, never>>,
    '/inside': RouteRecordInfo<'/inside', '/inside', Record<never, never>, Record<never, never>>,
    '/master': RouteRecordInfo<'/master', '/master', Record<never, never>, Record<never, never>>,
    '/masters': RouteRecordInfo<'/masters', '/masters', Record<never, never>, Record<never, never>>,
    '/media': RouteRecordInfo<'/media', '/media', Record<never, never>, Record<never, never>>,
    '/media-post': RouteRecordInfo<'/media-post', '/media-post', Record<never, never>, Record<never, never>>,
    '/nav': RouteRecordInfo<'/nav', '/nav', Record<never, never>, Record<never, never>>,
    '/policy': RouteRecordInfo<'/policy', '/policy', Record<never, never>, Record<never, never>>,
    '/prices': RouteRecordInfo<'/prices', '/prices', Record<never, never>, Record<never, never>>,
    '/procedures': RouteRecordInfo<'/procedures', '/procedures', Record<never, never>, Record<never, never>>,
    '/review': RouteRecordInfo<'/review', '/review', Record<never, never>, Record<never, never>>,
    '/review-inside': RouteRecordInfo<'/review-inside', '/review-inside', Record<never, never>, Record<never, never>>,
    '/tech': RouteRecordInfo<'/tech', '/tech', Record<never, never>, Record<never, never>>,
  }
}
